site_name: OGC API Learning Module
site_url: https://www.acceptatie.pdok.nl/leermodule
site_description: A learning module with background information and exercises to learn how to work with PDOK OGC APIs
repo_url: https://github.com/PDOK/leermodule-ogc-api/
edit_uri: edit/master/docs/
theme:
  language: en
  name: material
  palette:
   primary: custom
   accent: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
    - navigation.top
    - header.autohide
    - content.code.copy
  logo: assets/pdok.png
  favicon: assets/pdok.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search:
      lang: en
nav:
    - Introduction: index.md
    - Background information: 
        - Introduction: background-information/introduction.md
        - What is geoinformation?: background-information/what-is-geoinformation.md
        - What do Kadaster / PDOK do?: background-information/what-do-kadaster-pdok-do.md
        - What are OGC APIs?: background-information/what-are-ogc-apis.md
        - The importance of standards: background-information/the-importance-of-standards.md 
        - Reflection: background-information/reflection.md
    - OGC API - Tiles: 
        - Introduction: tiles/introduction.md
        - Explore OGC API - Tiles in the browser: tiles/explore-ogc-api-tiles-in-the-browser.md
        - Analyze an example map: tiles/analyze-an-example-map.md
        - Case study - Build a map with OGC API - Tiles: tiles/case-study-build-a-map-with-ogc-api-tiles.md
        - Reflection: tiles/reflection.md
    - OGC API - Features:
        - Introduction: features/introduction.md
        - Explore OGC API - Features in the browser: features/explore-ogc-api-features-in-the-browser.md
        - Query OGC API - Features with curl: features/query-ogc-api-features-with-curl.md
        - Case study - Analyze data with OGC API - Features in Python: features/case-study-analyze-data-with-ogc-api-features-in-python.md
        - Reflection: features/reflection.md
    - Wrap-up: wrap-up.md
    - Community: Community.md
    - References:
        - Sources: references/sources.md 

