site_name: OGC API Learning Module
site_url: https://www.acceptatie.pdok.nl/leermodule
site_description: A learning module with background information and exercises to learn how to work with PDOK OGC APIs
repo_url: https://github.com/PDOK/leermodule-ogc-api/
edit_uri: edit/master/docs/
theme:
  language: en
  name: material
  palette:
   primary: custom
   accent: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
    - navigation.top
    - header.autohide
    - content.code.copy
  logo: assets/pdok.png
  favicon: assets/pdok.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search:
      lang: en
nav:
    - Introduction: index.md
    - Background information: 
        - Introduction: achtergrondinformatie/Introductie.md
        - What is geoinformation?: achtergrondinformatie/Wat is geo-informatie.md
        - What do Kadaster / PDOK do?: achtergrondinformatie/Wat doet het Kadaster - PDOK.md
        - What are OGC APIs?: achtergrondinformatie/Wat zijn OGC APIs.md
        - The importance of standards: achtergrondinformatie/Het belang van standaarden.md 
        - Reflection: achtergrondinformatie/Terugblik.md
    - OGC API - Tiles: 
        - Introduction: tiles/Introductie.md
        - Explore OGC API - Tiles in the browser: tiles/Verken OGC API - Tiles in de browser.md
        - Analyze an example map: tiles/Analyseer een voorbeeldkaart.md
        - Case study - Build a map with OGC API - Tiles: tiles/Casus - Maak een kaart met OGC API - Tiles.md
        - Reflection: tiles/Terugblik.md
    - OGC API - Features:
        - Introduction: features/Introductie.md
        - Explore OGC API - Features in the browser: features/Verken OGC API - Features in de browser.md
        - Query OGC API - Features with curl: features/Bevraag OGC API - Features met curl.md
        - Case study - Analyze data with OGC API - Features in Python: features/Casus - Analyseer data met OGC API - Features met Python.md
        - Reflection: features/Terugblik.md
    - Wrap-up: Afronding.md
    - Community: Community.md
    - References:
        - Sources: referenties/features.md 

